In [1]:
from PIL import Image, ImageFilter

In [2]:
img = Image.open('ncu.jpg')
img.show()

In [7]:
print(img.size)
print(img.mode)
print(img.format)

(974, 497)
RGB
JPEG


In [4]:
#rotate image
img = img.rotate(90)
img.show()

In [46]:
#blur image
img = img.filter(ImageFilter.BLUR)
img.show()

In [47]:
#convert image to green scale
img = img.convert('L')
img.show()

In [4]:
import numpy as np
#convert image to numpy array
imgar = np.array(img)
print(imgar)
print(imgar.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 65  72  21]
  [ 65  71  23]
  [ 63  69  25]
  ...
  [ 65  90  51]
  [ 68  93  54]
  [ 75 100  61]]

 [[ 75  84  37]
  [ 76  85  40]
  [ 74  83  40]
  ...
  [ 66  91  52]
  [ 64  89  50]
  [ 58  83  44]]

 [[107 112  20]
  [111 117  31]
  [101 112  33]
  ...
  [ 60  85  43]
  [ 54  79  37]
  [ 55  80  40]]]
(497, 974, 3)


In [9]:
#remove red and blue channel
imgar[:, :, 0] = 0
#convert numpy array to image
imggr = Image.fromarray(imgar)
imggr.show()

In [10]:
imgar[:, :]

array([[[  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255],
        ...,
        [  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255]],

       [[  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255],
        ...,
        [  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255]],

       [[  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255],
        ...,
        [  0, 255, 255],
        [  0, 255, 255],
        [  0, 255, 255]],

       ...,

       [[  0,  72,  21],
        [  0,  71,  23],
        [  0,  69,  25],
        ...,
        [  0,  90,  51],
        [  0,  93,  54],
        [  0, 100,  61]],

       [[  0,  84,  37],
        [  0,  85,  40],
        [  0,  83,  40],
        ...,
        [  0,  91,  52],
        [  0,  89,  50],
        [  0,  83,  44]],

       [[  0, 112,  20],
        [  0, 117,  31],
        [  0, 112,  33],
        ...,
        [  0,  85,  43],
        [  0,  79,  37],
        [  0,  80,  40]]

In [11]:
height, width = img.size
image_data=img.load()
for loop1 in range(height):
    for loop2 in range(width):
        r,g,b = image_data[loop1,loop2]
        image_data[loop1,loop2] = 0,g,0

In [12]:
img.save('changed.jpeg')

In [5]:
shapes=Image.open('shapes.png')
shapes.show()
imgar1=np.array(shapes)
print(imgar1.shape)
imgar1[:,:,0]=0
imgar1[:,:,2]=0
imgreen=Image.fromarray(imgar1)
imgreen.show()

(400, 640, 3)


In [6]:
scaled=imgreen.resize((int(imgreen.size[0]/2),int(imgreen.size[1]/2)))
scaled.show()

In [7]:
rota=scaled.rotate(90)
rota.show()