In [37]:
import numpy as np

In [38]:
mask = np.array([[1, 1, 1], [0, 1, 0], [1, 0, 1]])
print("mask")
print(mask)
#rotate 180 degree
mask_rot = np.rot90(mask, 2)
print("mask 180")
print(mask_rot)

mask
[[1 1 1]
 [0 1 0]
 [1 0 1]]
mask 180
[[1 0 1]
 [0 1 0]
 [1 1 1]]


In [39]:
img = np.array([[1,1,1,0,0],[0,1,1,1,0],[0,0,1,1,1],[0,0,1,1,0],[0,1,1,0,0]])
print("img")
print(img)

img
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]


In [40]:
#Correlation
def apply_kernel(img, kernel):
	return np.sum(np.multiply(img, kernel))

def correlation(img, mask):
    arr=[]
    for i in range(len(img)-len(mask)+1):
        arr1=[]
        for j in range(len(img[0])-len(mask)+1):
            arr1.append(apply_kernel(img[i:i+3, j:j+3], mask))
        arr.append(arr1)
    return np.array(arr)
        
def convulation(img, mask):
    arr=[]
    for i in range(len(img)-len(mask_rot)+1):
        arr1=[]
        for j in range(len(img[0])-len(mask_rot)+1):
            arr1.append(apply_kernel(img[i:i+3, j:j+3], mask_rot))
        arr.append(arr1)
    return np.array(arr)

In [41]:
print("Correlation")
print(correlation(img, mask))
print("Convulation")
print(convulation(img, mask_rot))

Correlation
[[5 4 4]
 [3 5 4]
 [2 4 5]]
Convulation
[[4 4 5]
 [2 5 4]
 [3 4 4]]


In [42]:
from PIL import Image
image= Image.open('ncu.jpg')
img = np.array(image)
print("img")
print(img)

img
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 65  72  21]
  [ 65  71  23]
  [ 63  69  25]
  ...
  [ 65  90  51]
  [ 68  93  54]
  [ 75 100  61]]

 [[ 75  84  37]
  [ 76  85  40]
  [ 74  83  40]
  ...
  [ 66  91  52]
  [ 64  89  50]
  [ 58  83  44]]

 [[107 112  20]
  [111 117  31]
  [101 112  33]
  ...
  [ 60  85  43]
  [ 54  79  37]
  [ 55  80  40]]]


In [43]:
gaussian_mask = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]])
print("gaussian_mask")
print(gaussian_mask)

gaussian_mask
[[1 2 1]
 [2 4 2]
 [1 2 1]]


In [44]:
blur_img=convulation(img, gaussian_mask)
data = Image.fromarray(blur_img)
data.save('blur_img.png')

In [45]:
correlation_img=correlation(img, gaussian_mask)
data = Image.fromarray(correlation_img)
data.save('correlation_img.png')

In [ ]:
def blur_img(img, mask):
    arr=[]
    for i in range(len(img)-len(gaussian_mask)+1):
        arr1=[]
        for j in range(len(img[0])-len(gaussian_mask)+1):
            arr1.append(apply_kernel(img[i:i+3, j:j+3],gaussian_mask))
        arr.append(arr1)
    return np.array(arr)

In [ ]:
data = Image.fromarray(blur_img(img, gaussian_mask))
data.save('blur_img1.png')